name: Clean Workflow Runs
description: A GitHub Action to clean up old workflow runs
inputs:
  keep: 
    description: "存在数量"
    required: true
    default: '3'
  token:
    description: "Authorized secret GitHub Personal Access Token. Defaults to github.token"
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Clean
      shell: bash
      run: |
          echo "sa: ${{ inputs.keep }}"
          current_run_id=$(echo "$GITHUB_RUN_ID")
          runs=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$GITHUB_WORKFLOW/runs" \
            -H "Authorization: Bearer ${{ input.token }}" \
            -H "Accept: application/vnd.github.v3+json" | jq -r '.workflow_runs[].id')
          echo "$runs"
          keep_runs=$(echo "$runs" | head -n ${{ inputs.keep }})
          for run_id in $runs; do
            if [ "$run_id" != "$current_run_id" ] && [[ ! "$keep_runs" =~ "$run_id" ]]; then
              curl -s -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id" \
                -H "Authorization: Bearer ${{ inputs.token }}" \
                -H "Accept: application/vnd.github.v3+json" > /dev/null
            fi
          done
