name: Clean
description: 清除多余的流

runs:
  using: composite
  steps:
    - name: Cache node modules
      uses: actions/checkout@v4
      run: |
          # 获取当前工作流程运行的ID
          current_run_id=$(echo "$GITHUB_RUN_ID")

          # 获取当前仓库的工作流程运行列表
    
          runs=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/actions/workflows/my.yml/runs" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" | jq -r '.workflow_runs[].id')
          echo "$runs"
              # 计算要保留的工作流程运行ID
              keep_runs=$(echo "$runs" | head -n 3)

              # 删除不在保留列表中的工作流程运行
              for run_id in $runs; do
                if [ "$run_id" != "$current_run_id" ] && [[ ! "$keep_runs" =~ "$run_id" ]]; then
                  curl -s -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id" \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" > /dev/null
                fi
              done
     
