name: Build
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
env:
  IS_CI: 'true'
jobs:
  
  Windows:
    name: Windows
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      # - name: Setup Node Env
      #   uses: ./.github/actions/setup

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build src code
        run: |
          npm install
          npm ci
          git status --porcelain
          npm run pack:win

     
      - name: Generate file MD5
        run: |
          echo "下载软件app">> release.txt
          echo "version=$(bash ./version.sh)" >> $GITHUB_ENV
          cd build
          Get-FileHash *.exe,*.7z -Algorithm MD5 | Format-List
      - name: commit
        run: |
             git config --local user.email "tset@qq.com"
             git config --local user.name "test"
             git pull
             git add version.txt
             git commit -m "update $(date +'%Y-%m-%d %H:%M:%S')"
      - name:  Push changes
        uses:  ad-m/github-push-action@master
        with:  
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: 发布到release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          body_path: release.txt
          files: ./version.txt