name: myapp
on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 17 * * 5
  workflow_dispatch:
      inputs:
        environment:
          description: '是否手动输入版本号'
          required: true
          default: 'false'
          type: choice
          options:
            - true
            - false 
        version:
          description: '版本号'
          required: false
          default: 0.0.1
        
    
env:
  IS_CI: 'true'
jobs:
  
  Windows:
    name: Windows
    runs-on: windows-latest
    env:
      NPM_CACHE: '%APPDATA%\npm-cache'
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Node Env
        uses: ./.github/actions/setup

      - name: 手动版本号
        if: ${{ github.event.inputs.environment == 'true' }}
        run: |
          echo "version=${{ github.event.inputs.version }}" >> $env:GITHUB_ENV

      - name: 自动版本号
        if: ${{ github.event.inputs.environment == 'false' }}
        run: |
            $versionFile = "version.txt"
            if (-not (Test-Path $versionFile)) {
                Set-Content -Path $versionFile -Value "0.0.0"
            }
            $version = Get-Content -Path $versionFile
            $versionArray = $version.Split('.')
            $versionArray[2] = [int]$versionArray[2] + 1
            if ($versionArray[2] -eq 20) {
                $versionArray[2] = 0
                $versionArray[1] = [int]$versionArray[1] + 1
                if ($versionArray[1] -eq 20) {
                    $versionArray[1] = 0
                    $versionArray[0] = [int]$versionArray[0] + 1
                }
            }
            $newVersion = $versionArray -join '.'
            Set-Content -Path $versionFile -Value $newVersion
            echo "version=$newVersion" >> $env:GITHUB_ENV
          
      - name: Commit version.txt
        run: |
            git config --local user.email "your_email@example.com"
            git config --local user.name "Your Name"
            git add version.txt
            git commit -m "Update version.txt"
            git push
      - name: Build src code
        run: |
          git status --porcelain
          npm run pack:win

      
      - name: Generate file MD5
        run: |
          echo "发布文件" >> release.txt
          ls build
          Get-FileHash build/*.exe,build/*.7z -Algorithm MD5 | Format-List

          
      - name: 发布到release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          body_path: release.txt
          files: ./build/*.exe