name: Build
on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 17 * * 5
  workflow_dispatch:

env:
  IS_CI: 'true'
jobs:
  
  Windows:
    name: Windows
    runs-on: windows-latest
    env:
      NPM_CACHE: '%APPDATA%\npm-cache'
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Node Env
        uses: ./.github/actions/setup

      # - name: Build src code
      #   run: |
      #     git status --porcelain
      #     npm run pack:win

      - name: Set version
        run: |
          echo "version=$(bash ./version.sh)" >> $GITHUB_ENV
      - name: show version
        run: |
          echo "version=${{ env.version }}"
      
      # - name: Generate file MD5
      #   run: |
      #     echo "下载软件app" >> release.txt
      #     ls build
      #     Get-FileHash build/*.exe,build/*.7z -Algorithm MD5 | Format-List

      # - name: commit
      #   run: |
      #     git config --local user.email "test@example.com"
      #     git config --local user.name "test"
      #     git pull origin master
      #     git add release.txt
      #     git commit -m "Update version.txt"
          
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:  
      #     branch: master
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: 发布到release
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ env.VERSION }}
      #     body_path: release.txt
      #     files: ./build/*.exe