name: Post Request

on:
    workflow_dispatch:
        inputs:
          number:
            description: '输入题目数量'
            required: true
            default: '100'
          cookie:
            description: 'cookie'
            default: cookie="sid=1100891;persistent=cIhKDhswJMdZWRYFmTuyY9WdnZGpd52edSYbAPeSuTP6KVxwhlLnCcMeEo0L515H2EymJrwmDCi99kiaCKrqfQ==;sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%22118039924%22%2C%22first_id%22%3A%2218b4faca706f54-05d58e7c770956-17525634-1296000-18b4faca7072433%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%2218b4faca706f54-05d58e7c770956-17525634-1296000-18b4faca7072433%22%2C%22identities%22%3A%22eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMThiNGZiMDY3YmExNGMyLTBkOWQ2OGZmYTYxOWZjOC0xNzUyNTYzNC0xMjk2MDAwLTE4YjRmYjA2N2JiMjcxNSIsIiRpZGVudGl0eV9sb2dpbl9pZCI6IjExODAzOTkyNCJ9%22%2C%22history_login_id%22%3A%7B%22name%22%3A%22%24identity_login_id%22%2C%22value%22%3A%22118039924%22%7D%7D; sess=srYvurm1EHqL+5JsPlz/c4dggT+wkaq+nxkbMrQO2n7X554711INy/sLGoLHpi0BD9enKAWD6SpZE778+myLajJEc9PMsLyEcMXmf7JD34U=; userid=118039924; acw_tc=0bd17c6617168031159852753ec871911f26290ddc48c823ae338a909ebb3a"
            type: string
jobs:
  post_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install curl and jq
      run: sudo apt-get update && sudo apt-get install -y curl jq

    - name: Post request
      run: |
        url="https://tiku.fenbi.com/activity/userquiz/updateUserQuestionInfo?sheetType=151&questionCount=${{ github.event.inputs.number }}&yearScope=0&correctRatioLow=0&correctRatioHigh=1&app=web&kav=100&av=100&hav=100&version=3.0.0.0"

        cookie="${{ github.event.inputs.cookie }}"
        response=$(curl -s -X POST -H "Content-Type: application/json" -H "Cookie: $cookie"  $url)
        msg=$(echo $response | jq -r '.msg')

        if [ "$msg" = "SUCCESS" ]; then
             echo "修改题目数量为${{github.event.inputs.number}}成功"
        else
             echo "修改题目数量为${{github.event.inputs.number}}失败"
        fi