name: Build

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
env:
  IS_CI: 'true'

jobs:
  
  Windows:
    name: Windows
    runs-on: windows-latest
    env:
      NPM_CACHE: '%APPDATA%\npm-cache'
    # needs: CheckCode
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Node Env
        uses: ./.github/actions/setup

      - name: Build src code
        run: |
          git status --porcelain
          npm run pack:win

     
      - name: Generate file MD5
        run: |
          echo "下载软件app">> release.txt
          cd build
          Get-FileHash *.exe,*.7z -Algorithm MD5 | Format-List

      - name: 发布到release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "1.1.1"
          body_path: release.txt
          files: ./build/*.exe

  
