name: Build

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
env:
  IS_CI: 'true'

jobs:
  
  Windows:
    name: Windows
    runs-on: windows-latest
    # env:
    #   NPM_CACHE: '%APPDATA%\npm-cache'
    # needs: CheckCode
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      # - name: Setup Node Env
      #   uses: ./.github/actions/setup
        
      - name: 设置变量
        id: compile
        run: |
          echo "version=$(bash version.sh)" >> $GITHUB_ENV
          echo "bgcode=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          echo "下载软件app">> release.txt
      # - name: Build src code
      #   run: |
      #     git status --porcelain
      #     npm run pack:win

     
      - name: Generate file MD5
        run: |
          # cd build
          # Get-FileHash *.exe,*.7z -Algorithm MD5 | Format-List
      - name: commit
        run: |
             git config --local user.email "tset@qq.com"
             git config --local user.name "test"
             git pull
             git add version.txt
             git commit -m "update $(date +'%Y-%m-%d %H:%M:%S')"
      - name:  Push changes
        uses:  ad-m/github-push-action@master
        with:  
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: 发布到release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version}}
          body_path: release.txt
          files: ./version.txt

  # Mac:
  #   name: Mac
  #   runs-on: macos-latest
  #   env:
  #     NPM_CACHE: $HOME/.npm
  #   # needs: CheckCode
  #   steps:
  #     - name: Check out git repository
  #       uses: actions/checkout@v4

  #     - name: Install python3 setuptools
  #       run: |
  #         mkdir ~/.venv
  #         python3 -m venv ~/.venv
  #         source ~/.venv/bin/activate
  #         python3 -m pip install setuptools
  #     - name: 设置变量
  #       id: compile
  #       run: |
  #         echo "version=$(bash version.sh)" >> $GITHUB_ENV
  #         echo "下载软件app">> release.txt
  #     - name: Setup Node Env
  #       uses: ./.github/actions/setup

  #     - name: Build src code
  #       run: |
         
  #         git status --porcelain
  #         npm run pack:mac

  #     - name: 发布到release
  #       uses: softprops/action-gh-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ env.VERSION }}
  #         body_path: release.txt
  #         files: ./build/*.dmg

  #     - name: Generate file MD5
  #       run: |
  #         cd build
  #         md5 *.dmg

