name: test
on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 17 * * 5
  workflow_dispatch:
env:
    IS_CI: 'true'
jobs:
    Windows:
        name: Windows
        runs-on: windows-latest
        env:
          NPM_CACHE: '%APPDATA%\npm-cache'
        steps:
          - name: Check out git repository
            uses: actions/checkout@v4
    
          - name: Set version
            run: |
                $versionFile = "version.txt"
                if (-not (Test-Path $versionFile)) {
                    Set-Content -Path $versionFile -Value "0.0.0"
                }
                $version = Get-Content -Path $versionFile
                $versionArray = $version.Split('.')
                $versionArray[2] = [int]$versionArray[2] + 1
                if ($versionArray[2] -eq 20) {
                    $versionArray[2] = 0
                    $versionArray[1] = [int]$versionArray[1] + 1
                    if ($versionArray[1] -eq 20) {
                        $versionArray[1] = 0
                        $versionArray[0] = [int]$versionArray[0] + 1
                    }
                }
                $newVersion = $versionArray -join '.'
                Set-Content -Path $versionFile -Value $newVersion
                echo "version=$newVersion" >> $env:GITHUB_ENV
              
          - name: Commit version.txt
            run: |
                git config --local user.email "your_email@example.com"
                git config --local user.name "Your Name"
                git add version.txt
                git commit -m "Update version.txt"
                git push
          - name: show version
            run: |
              echo "version=${{ env.version }}"