name: test
on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 17 * * 5
  workflow_dispatch:
env:
    IS_CI: 'true'
jobs:
    Windows:
        name: Windows
        runs-on: windows-latest
        env:
          NPM_CACHE: '%APPDATA%\npm-cache'
        steps:
          - name: Check out git repository
            uses: actions/checkout@v4
    

          - name: show version
            run: |
              echo "version=${{ env.version }}"