name: Limit Recent Workflow Runs

on:
  workflow_dispatch:
    inputs:
        keep:
            description: '是否保留旧版本'
            required: true
            default: 5
      
jobs:
  cleanup_old_runs:
    runs-on: ubuntu-latest

    steps:
      - name: 检查环境
        uses: actions/checkout@v4

      - name: Clean
        uses: ./.github/actions/clean
        with:
          keep: ${{ github.event.inputs.keep }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


