name: Build
on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 17 * * 5
  workflow_dispatch:
env:
    IS_CI: 'true'
jobs:
    Windows:
        name: Windows
        runs-on: windows-latest
        env:
          NPM_CACHE: '%APPDATA%\npm-cache'
        steps:
          - name: Check out git repository
            uses: actions/checkout@v4
    
          - name: Set version
            run: |
              if [ ! -f version.txt ]; then
                    echo "0.0.0" > version.txt
              fi 
              VERSION=$(cat version.txt)
              IFS='.' read -r -a versionArray <<< "$VERSION"
              ((versionArray[2]++))
              if [ "${versionArray[2]}" -eq 20 ]; then
                  versionArray[2]=0
                 ((versionArray[1]++))

               # 如果第二位数字达到了10，则将它设为0并递增第一位数字
                 if [ "${versionArray[1]}" -eq 20 ]; then
                    versionArray[1]=0
                    ((versionArray[0]++))
                 fi
              fi
              echo "${versionArray[0]}.${versionArray[1]}.${versionArray[2]}" > version.txt
              echo "version=$(cat version.txt)" >> $GITHUB_ENV
          - name: show version
            run: |
              echo "version=${{ env.version }}"