name: test
on:
  workflow_dispatch:
      inputs:
        version:
          description: '版本号'
          required: false
          default: 0.0.1
        keeps:
          description: '启动删除'
          required: true
          default: true
          type: boolean
        keep:
          description: '是否保留旧版本'
          required: true
          default: 3
          type: number
env:
  IS_CI: 'true'
jobs:
    liunx:
        if: ${{ github.event.inputs.keeps == 'true' }}
        runs-on: ubuntu-latest
        steps:
          - name: 检查环境
            uses: actions/checkout@v4
          - name: 删除
            shell: bash
            run: |
                current_run_id=$(echo "$GITHUB_RUN_ID")
                runs=$(curl -s -X GET "https://api.github.com/repos/${{ github.repository }}/actions/runs" \
                  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" | jq -r '.workflow_runs[].id')
                echo "$runs"
                    keep_runs=$(echo "$runs" | head -n ${{ github.event.inputs.keep }})
                    for run_id in $runs; do
                      if [ "$run_id" != "$current_run_id" ] && [[ ! "$keep_runs" =~ "$run_id" ]]; then
                        curl -s -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id" \
                          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" > /dev/null
                      fi
                    done
           
