name: test
on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 17 * * 5
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: $(date "+%Y-%m-%d")
env:
    IS_CI: 'true'
jobs:
    Windows:
        name: Windows
        runs-on: windows-latest
        env:
          NPM_CACHE: '%APPDATA%\npm-cache'
        steps:
          - name: Check out git repository
            uses: actions/checkout@v4
    
          - name: Set version
            shell: pwsh
            run: |
              $newVersion = .\version.sh
              echo "version=${{ github.event.inputs.environment }}" >> $env:GITHUB_ENV
              # echo "version=$newVersion" >> $env:GITHUB_ENV

          - name: show version
            run: |
              echo "version=${{ env.version }}"

             
              
